# Generated by Django 4.1.2 on 2022-10-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0004_remove_song_artist_album_album_cover_album_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
